name: Bicep CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs the bicep CLI action - individual files
      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.3
        with:
          files: thethingsstack-on-azure.bicep

      # Checks the result
      - name: Check the result
        shell: bash
        run: |
          shopt -s globstar
          ls -altR **/thethingsstack-on-azure*.*
